version: "3"
services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - "mosquitto:/mosquitto"
    ports:
      - "1883:1883"

  node-red:
    depends_on:
      - broker
    image: nodered/node-red
    volumes:
      - "./node-red:/data"
    ports:
      - "1880:1880"
volumes:
  mosquitto:
